orion.api-base-url=http://orion:1026/ngsi-ld/v1
orion.health-url=http://orion:1026/version
orion.context-url=http://context-server/datamodels.context-ngsi.jsonld

# Visualize Control API on host; change to service name when Visualize is containerized
app.control-api.base-url=http://host.docker.internal:9090
app.context-provider.health-url=http://context-server/datamodels.context-ngsi.jsonld

spring.datasource.url=jdbc:postgresql://postgres:5432/traffic
