orion.api-base-url=http://localhost:1026/ngsi-ld/v1
orion.health-url=http://localhost:1026/version
orion.context-url=http://localhost:3004/datamodels.context-ngsi.jsonld

app.control-api.base-url=http://localhost:9090
app.context-provider.health-url=http://localhost:3004/datamodels.context-ngsi.jsonld
