"""K-7 Bronze v2 processor — Raw ClickHouse → Bronze/Quarantine."""

MIGRATION_VERSION = "k7-bronze-v2-v1"
PROCESSOR_NAME = "kafka-bronze-v2"
PROCESSOR_VERSION = "1.0.0"
BRONZE_SCHEMA_VERSION = "1.0.0"
SOURCE_CONTRACT_VERSION = "2.0.0"

STATUS_STORED = "STORED"
STATUS_QUARANTINED = "QUARANTINED"
STATUS_RAW_QUARANTINE_SKIPPED = "RAW_QUARANTINE_SKIPPED"
STATUS_IDEMPOTENT_SKIP = "IDEMPOTENT_SKIP"

DEST_ENTITY = "ENTITY"
DEST_RUN = "RUN"
DEST_BRONZE_QUARANTINE = "BRONZE_QUARANTINE"

NAMESPACE_LIVE = "live"
